name: ✨ Feature Request
description: 새로운 기능을 제안해주세요!
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        기능 제안을 해주셔서 감사합니다!
        아이디어를 가능한 자세히 설명해주시면 검토에 도움이 됩니다.

  - type: textarea
    id: problem
    attributes:
      label: 해결하고자 하는 문제
      description: 이 기능이 해결하려는 문제가 무엇인가요?
      placeholder: |
        예: "배틀 결과를 분석할 때 항상 수동으로 데이터를 정리해야 해서 불편합니다..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결책
      description: 어떤 기능을 원하시나요?
      placeholder: 제안하시는 기능을 자세히 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 대안
      description: 고려해본 다른 방법이 있나요?
      placeholder: 다른 해결 방법이나 대안을 알려주세요.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: 관련 컴포넌트
      description: 어떤 컴포넌트에 관련된 기능인가요?
      options:
        - API Service (Go)
        - ML Service (Python)
        - Attacker Module
        - Defender Module
        - Training Pipeline
        - MLOps
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 기능이 얼마나 중요한가요?
      options:
        - Low - 있으면 좋음
        - Medium - 중요하지만 급하지 않음
        - High - 매우 필요함
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 추가 정보
      description: 기능 요청에 대한 추가 정보나 스크린샷이 있다면 알려주세요.
      placeholder: 참고 자료, 예시, 스크린샷 등
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: 제출 전 확인해주세요
      options:
        - label: 비슷한 기능 요청이 이미 있는지 검색했습니다.
          required: true
        - label: 이 기능이 프로젝트 범위에 맞는다고 생각합니다.
          required: false
